### ISSUE TITLE
id.txt

### ISSUE THREAD

**Issue by wh1090220084** [LiuAoyu1998/STIDGCN#1]
如何生成id.txt?

**Comment by LiuAoyu1998** [comment]
你好！id.txt是对节点进行编号生成的，最新的邻接矩阵生成方法generate_datasets.py 已更新。如果你想获得除PEMS08数据集以外的CSV文件，可以参考[STSGCN](https://github.com/Davidham3/STSGCN)分享的原始数据。此外，我们提供了处理后的数据，你可通[百度云分享链接](https://pan.baidu.com/s/1pbRUmRg_Y69KRNEuKZParQ?errmsg=Auth+Login+Params+Not+Corret&errno=2&ssnerror=0#list/path=%2F)获取，密码**1s5t**。

**Comment by wh1090220084** [comment]
好的！感谢！

**Comment by wh1090220084** [comment]
最新的生成代码貌似有问题！ 旧的版本保存三个字段，新的保存了一个！ 还有id.txt。是把from和to这两列的字段去重后重新排列得到的吗？ 我看到id.txt里面的id序列是0，2，3，4，5....... 缺少1，所以我就不知道id.txt是怎么生成出来的！ 我刚接触到这个方向。小白一枚！

**Comment by LiuAoyu1998** [comment]
之前的id.tx是我自己生成的，就是遍历from和to列，用简单的遍历，可以理解为遍历出节点的编号，然后存入txt文件。

**Comment by LiuAoyu1998** [comment]
除了PEMS03需要id.txt其他数据集不需要的。id.txt生成比较简单，就是通过遍历csv文件中的from和to里面的数值，保存并剔除重复数值。以PEMS08为例，有170个节点，那csv中对应的是0，1，2，...,169编号，因为是从0开始编号节点，所以生成邻接矩阵并不需要这个，但是你观察PEMS03的数据就会发现，它初始编号不是0，这也是代码里为什么出现不是0要进行txt映射。

然后generate_datasets.py，目的是通过遍历csv文件，实现生成节点邻接矩阵和边邻接矩阵，实际上STIDGCN只用到了节点邻接矩阵，并没有用到边邻接矩阵。运行后产生两个矩阵的pkl文件，一个是节点邻接矩阵，即1表示两个节点存在连接，0表示两个节点没有连接，另一个边邻接矩阵，可以理解为把表示连接关系的1变成两个节点的距离（CSV文件中的第三列）。
3✖️3节点邻接矩阵
![image](https://user-images.githubusercontent.com/102887543/195983117-7764eeb5-09c2-4011-9e18-069c11fc6fd5.png)
3✖️3边邻接矩阵
![image](https://user-images.githubusercontent.com/102887543/195983164-e5c23e95-136a-44c1-9fec-66b4fc4b92a1.png)

然后你查看train.py后会发现64行，sensor_ids, sensor_id_to_ind, adj_mx = util.load_adj(args.adjdata, args.adjtype)，这里利用到了之前生成的节点矩阵，并利用节点邻接矩阵生成两个过渡矩阵（注意并没有用到边邻接矩阵）送入至模型，具体看utils.py的第147行。

由于最新的generate_datasets.py并不是原创代码，只是在[前人基础](https://github.com/zezhishao/D2STGNN/blob/d5ab6e2296911ce49ad2b97b299de7f9394f47f6/datasets/raw_data/PEMS08/generate_adj_mx.py)上加以改进，可能会出现冗余。所以只能和你说这个代码实现了什么功能，具体细节，可能还需要你自己在参考下[GWN](https://github.com/sshleifer/Graph-WaveNet/blob/master/gen_adj_mx.py)。目前已经对代码再次精简。
