### ISSUE TITLE
How did the adj_PEMS08.pkl in the downloaded data come about?

### ISSUE THREAD

**Issue by ujnzl** [LiuAoyu1998/STIDGCN#2]
In generate_datasets.py and gen_adj_mx.py, only the resulting matrix of nodes and edges is processed, with no further processing.

**Comment by ujnzl** [comment]
在train.py中使用的adj_PEMS08.pkl无法通过generate_datasets.py和gen_adj_mx.py生成，换成新数据的话在train中使用什么矩阵呢？

**Comment by LiuAoyu1998** [comment]
你好！adj_PEMS08.pkl可以通过gen_adj_mx.py生成，gen_adj_mx.py代码中生成的文件名没有保持统一，现已更改。邻接矩阵是根据原始数据集附带的csv文件生成的，只需要更改gen_adj_mx.py的“data_name”即可，例如PEMS04，data_name = "PEMS04"。

**Comment by ujnzl** [comment]
您好！我仔细阅读了之后，发现您刚修改的gen_adj_mx.py生成的adj_PEMS08.pkl与train.py中的adj_PEMS08.pkl不相同。
首先tran.py中的adj_PEMS08.pkl包含sensor_ids, sensor_id_to_ind, adj_mx三列，而您刚刚修改的gen_adj_mx.py只保存了adj_mx，其次gen_adj_mx.py生成的adj_mx和tran.py中使用的adj_mx也不相同。

**Comment by ujnzl** [comment]
您好！我仔细阅读了之后，发现您刚修改的gen_adj_mx.py生成的adj_PEMS08.pkl与train.py中的adj_PEMS08.pkl不相同。
首先tran.py中的adj_PEMS08.pkl包含sensor_ids, sensor_id_to_ind, adj_mx三列，而您刚刚修改的gen_adj_mx.py只保存了adj_mx，其次gen_adj_mx.py生成的adj_mx和tran.py中使用的adj_mx也不相同。

Seraser
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiuAoyu1998/STIDGCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 下午5:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiuAoyu1998/STIDGCN] How did the adj_PEMS08.pkl in the downloaded data come about? (Issue #2)





 
你好！adj_PEMS08.pkl可以通过gen_adj_mx.py生成，gen_adj_mx.py代码中生成的文件名没有保持统一，现已更改。邻接矩阵是根据原始数据集附带的csv文件生成的，只需要更改gen_adj_mx.py的“data_name”即可，例如PEMS04，data_name = "PEMS04"。

**Comment by LiuAoyu1998** [comment]
您好，train.py中的sensor_ids, sensor_id_to_ind, adj_mx只用到了adj_mx，您可以直接删除前两个（sensor_ids, sensor_id_to_ind）。
“其次gen_adj_mx.py生成的adj_mx和tran.py中使用的adj_mx也不相同。”这句话我没有太理解，gen_adj_mx.py生成的adj_mx就是为了传入至train.py中。

**Comment by LiuAoyu1998** [comment]
您好，我刚刚测试了代码，确实发现了问题。这个问题主要来自gen_adj_mx.py在之前简化一次，忘记更新train.py和utils.py，现在已经修改了这个问题。

**Comment by ujnzl** [comment]
好的，感谢您的交流。
