### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by wy123go** [LiuAoyu1998/STIDGCN#3]

**Comment by liuaoy** [comment]
您好！
为了和前人工作保持一致，数据集是按照[STSGCN](https://github.com/wanhuaiyu/STSGCN)的处理方式进行划分的，即滑动窗口划分。12个时间片预测接下来的12个时间片，即历史1小时的数据预测未来一小时的数据。
数据集的其他细节如下：
![image](https://user-images.githubusercontent.com/45134622/205240781-3ad9f6bd-7047-492f-97a9-9cd473f47e60.png)

**Comment by LiuAoyu1998** [comment]
您好，数据集的处理方式和前人工作[STSGCN](https://github.com/wanhuaiyu/STSGCN)保持一致，即利用历史1小时的数据去预测未来1小时的数据。
数据集细节如下：
![image](https://user-images.githubusercontent.com/102887543/205241475-393fb1f8-f2af-4fe2-9c35-8dcf4b9fa5dd.png)
处理方式：训练集：验证集：测试集为6:2:2。Z-score归一化处理。

**Comment by wy123go** [comment]
非常感谢您的回复！
我跑了AGCRN的03数据集，因为embed_dim对这个模型的影响非常大，我取embed_dim=10跑的结果如下，mape过大了。想请教一下您当时做对比实验时，03数据集和07数据集的参数设置是怎么样的呢？
03数据集的运行结果如下：





鹅卵石臻于完美
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiuAoyu1998/STIDGCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiuAoyu1998/STIDGCN] 数据集 (Issue #3)





 
您好，数据集的处理方式和前人工作STSGCN保持一致，即利用历史1小时的数据去预测未来1小时的数据。
 数据集细节如下：
 
 处理方式：训练集：验证集：测试集为6:2:2。Z-score归一化处理。

**Comment by LiuAoyu1998** [comment]
03这个数据集本身所有模型就不太稳定。一般特征通道数（GCN的通道数，卷积的通道数）设置为64，您说的embed_dim是自适应邻接矩阵的N*embed_dim的维度吗？如果是这个一般也是10。

**Comment by wy123go** [comment]
您好！这几天我又试了下您的说法的配置文件，整个模型预测的MAPE还是太大了，如下图。您能方便发布一下您当时跑对比实验时的AGCRN的源代码吗?我用您的再去尝试一下。因为团队确实没有其他人做该方向的研究，试错了许久。





鹅卵石臻于完美
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiuAoyu1998/STIDGCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 下午4:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiuAoyu1998/STIDGCN] 数据集 (Issue #3)





 
03这个数据集本身所有模型就不太稳定。一般特征通道数（GCN的通道数，卷积的通道数）设置为64，您说的embed_dim是自适应邻接矩阵的N*embed_dim的维度吗？如果是这个一般也是10。

**Comment by LiuAoyu1998** [comment]
您好！我并没有复现AGCRN，如果您想复现AGCRN的结果，您可以使用Zezhi Shao的项目https://github.com/zezhishao/BasicTS ，里面可以复现AGCRN的结果。

**Comment by wy123go** [comment]
您好！Zezhi Shao的项目里这只是数据集的配置文件吧。





鹅卵石臻于完美
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiuAoyu1998/STIDGCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月6日(星期二) 晚上7:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiuAoyu1998/STIDGCN] 数据集 (Issue #3)





 
您好！我并没有复现AGCRN，如果您想复现AGCRN的结果，您可以使用Zezhi Shao的项目https://github.com/zezhishao/BasicTS，里面可以复现AGCRN的结果。

**Comment by LiuAoyu1998** [comment]
您好，不只是数据集的配置文件。您可以阅读他的readme文件，一步一步配置，实现其内置的baseline。我通过他的代码可以成功复现多种模型。

**Comment by wy123go** [comment]
您好，十分感谢！我来试一下。




鹅卵石臻于完美
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiuAoyu1998/STIDGCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月6日(星期二) 晚上8:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiuAoyu1998/STIDGCN] 数据集 (Issue #3)





 
您好，不只是数据集的配置文件。您可以阅读他的readme文件，一步一步配置，实现其内置的baseline。我通过他的代码可以成功复现多种模型。
