### ISSUE TITLE
你好，我想问一下邻接矩阵是如何计算的

### ISSUE THREAD

**Issue by Azusa-Yuan** [LiuAoyu1998/STIDGCN#4]
我发现您仓库里的adj_PEMS08.pkl，和您仓库里脚本生成的adj_PEMS08.pkl并不一致。1、邻接矩阵不同，脚本生成的邻接矩阵是0-1矩阵，而仓库里的不是 2、格式不同，脚本生成的adj_PEMS08.pkl仅有邻接矩阵并没有其它信息

**Comment by LiuAoyu1998** [comment]
您好！脚本生成，脚本是指哪里？

**Comment by Azusa-Yuan** [comment]
> 您好！脚本生成，脚本是指哪里？

仓库里的gen_adj_mx.py

**Comment by LiuAoyu1998** [comment]
您好！我检查了这个问题，发现之前在与其他人交流时，误把不同工作弄混了。这里的邻接矩阵生成方法借鉴了DCRNN。
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/102887543/209129736-6969464b-537f-4f6b-838c-245945b6126c.png">
我现在重新上传了gen_adj_mx.py和id.txt。感谢您的交流！

**Comment by Azusa-Yuan** [comment]
好的，我明白了，感谢您的及时回复

**Comment by LiuAoyu1998** [comment]
不客气，也感谢您的讨论与交流！
