### ISSUE TITLE
数据集的问题

### ISSUE THREAD

**Issue by Yuwangzhi** [LiuAoyu1998/STIDGCN#5]
您好，我看您自己生成了nyc-bike和nyc-taxi数据集，但是我无法按照您给的链接生成对应的时间戳（读取h5文件的时候有问题），请问可以公开另外三个数据吗？nyc-bike的pick up和nyc-taxi的pick up、drop off？万分感谢

**Comment by LiuAoyu1998** [comment]
您好，这个链接提供了所有处理好的数据集哦（带有time of day和time of week的时间戳），https://drive.google.com/drive/folders/1-5hKD4hKd0eRdagm4MBW1g5kjH5qgmHR

**Comment by LiuAoyu1998** [comment]
不过要注意的是，我们是按照6:2:2的比例划分训练、验证、测试集，所有baseline也是基于这个设置进行实验。

**Comment by Yuwangzhi** [comment]
谢谢您！我明天拿我的模型试一下，我在您公开的那个数据集上做到了 1.86 的 mae，所以想尝试一下别的。
另外，我 follow 您这篇论文一段时间了，您写的很好，效果也很好，最近更新了模型，是因为审稿人提的要求吗？还是说为了效果而增加了时间嵌入？
我尝试过，简单的时空嵌入加上 tcn 的结构，就可以达到更优的水平。这是不是也一定程度上说明这个领域已经达到了一定的瓶颈。

**Comment by LiuAoyu1998** [comment]
您好，感谢您的认可，以及对您取得不错效果表示祝贺。

当前工作确实在审稿中，具体细节目前不太方便透露，还望理解。当前论文与目前公开的版本也有很大差异。加入时间嵌入确实可以提高，但是并不能起到核心提升作用。时间嵌入只能说是一个锦上添花的做法。

此外您提到时空嵌入加上tcn，这种做法应该是受到多方面的启发，比如[STID](https://github.com/zezhishao/STID)那篇优秀的短文。我个人觉得空间嵌入挺重要的，这个空间嵌入最早可以追溯到GWN的自适应邻接矩阵，虽然叫法不一，但是本质上都是定义与节点相关的可训练参数。现有的很多SOTA方法都会定义这种与节点相关的可训练参数，这也是GWN作为一个19年模型始终久经不衰的原因。我个人认为当前领域在模型架构设计方面或许已经到达了瓶颈，很难出现大幅的性能提升。就目前的研究趋势，如何结合新的学习范式进行交通预测或许慢慢成为研究的重点，例如模型设计+自监督学习（对比学习、预训练学习）、模型设计+LLM方法、模型设计+元学习/迁移学习（小样本交通预测）、模型设计+持续学习。

**Comment by Yuwangzhi** [comment]
感谢您的回答和对我工作的认可！
我从今年年初的时候就已经意识到这个领域的瓶颈性，并做了部分工作：在 flow 数据集上用嵌入代替 gcn，发现得到了更好的效果。在 flow 数据集上去除预定义图，搭建更有效的图结构，并用 gcn 取得了更好的效果。在 speed 数据集上加上时间嵌入，取得了接近 sota 的效果。
然而，我发现我的工作目标和 stid 的类似，且他做的更快（效果一般）。
并且，今年我 follow 了一下 stid 和 d2stgnn 的作者 shao，他写了一篇ts 的综述，目前在谷歌学术上可以搜到预发表的版本，他总结了这个领域的现状，已经数据集之间的异质性（基于 basicTS）做的，您可以阅读一下～
您所说的 future works 我也在研究，但设计的技术多，有点偏移了本领域的主要研究目的，所以我也在慎重考虑。
最后，祝您的论文录用顺利！高产！

**Comment by LiuAoyu1998** [comment]
加油！也祝您一切顺利！
